name: Cleanup on branch removal

on: [ delete ]

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
      - name: Cleanup
        run: COMPOSE_PROJECT_NAME=${{ env.BRANCH_NAME }} docker-compose down --volumes  --remove-orphans --rmi all
